global:
  scrape_interval: 15s
  evaluation_interval: 15s

storage:
  exemplars:
    max_exemplars: 100000

rule_files:
  - /etc/prometheus/rules/recording.rules.yml
  - /etc/prometheus/rules/alerts.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']


remote_write:
  - url: http://mimir:9009/api/v1/push
    headers:
      X-Scope-OrgID: team-checkout
    queue_config:
      capacity: 10000
      max_shards: 10
      max_samples_per_send: 2000
    
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: worker
    file_sd_configs:
      - files: ['/etc/prometheus/targets/worker.json']
        refresh_interval: 30s

  - job_name: 'api'
    file_sd_configs:
      - files: ['/etc/prometheus/targets/api.json']
        refresh_interval: 30s
    relabel_configs:
      - target_label: environment
        replacement: dev
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_gc_.*|go_memstats_.*'
        action: drop

  - job_name: node-exporter
    file_sd_configs:
      - files: ['/etc/prometheus/targets/node.json']
        refresh_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_gc_.*|go_memstats_.*'
        action: drop
        

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
