events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    default_type text/plain;
    types {
        text/plain md markdown;
        text/plain txt;
    }
    server {
        listen 80;
        root /usr/share/nginx/html;
        location /runbooks/ {
            autoindex off;
        }
    }
}
