events {}

stream {
  upstream otlp {
    # no `least_conn`, no `hash $remote_addr`, no session persistence.
    # plain round-robin on new TCP connections — deliberately naive.
    server otel-collector-gateway:4317;
    server otel-collector-gateway-2:4317;
  }

  server {
    listen 4317;
    proxy_pass otlp;
  }
}