apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: default                        
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 15s