apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      # metric → trace (exemplar linking)
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
          urlDisplayLabel: '🔍 View Trace in Tempo' 

  - name: Mimir
    type: prometheus
    uid: mimir
    url: http://mimir:9009/prometheus

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      # log → trace (derived field linking)
      derivedFields:
        - name: TraceID
          matcherType: regex
          matcherRegex: '"trace_id":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: tempo
          urlDisplayLabel: '🔍 View Trace in Tempo' #  Keep this as urlLabel (Loki uses this)
    secureJsonData:
      httpHeaderValue1: fake

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    jsonData:
      # trace → logs (log correlation)
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: 'service.name'
            value: 'service'
        customQuery: false
      tracesToMetrics:
        datasourceUid: prometheus
      tracesToProfiles:
        datasourceUid: pyroscope
        profileTypeId: wall:cpu:nanoseconds:wall:nanoseconds
        tags:
           - key: 'service.name'
             value: 'service_name'

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope:4040
    jsonData:
      backendType: pyroscope
