apiVersion: v1
kind: ConfigMap
metadata: { name: api-config }
data:
  AWS_ENDPOINT: "http://localstack:4566"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  TOPIC_ARN: "arn:aws:sns:us-east-1:000000000000:orders"
  OTEL_SERVICE_NAME: "api"
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: api, labels: { app: api } }
spec:
  replicas: 1
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
        - name: api
          image: obs-api:day41
          imagePullPolicy: Never       # image only exists via kind load, never pull
          ports: [{ containerPort: 8080 }]
          envFrom: [{ configMapRef: { name: api-config } }]
---
apiVersion: v1
kind: Service
metadata: { name: api }
spec:
  selector: { app: api }
  ports: [{ port: 8080, targetPort: 8080 }]