apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
  namespace: default
data:
  beyla-config.yml: |
    discovery:
      services:
        - k8s_deployment_name: "api"
          k8s_namespace: "default"
    otel_metrics_export:
      endpoint: http://otel-gateway-opentelemetry-collector.observability.svc.cluster.local:4317
    otel_traces_export:
      endpoint: http://otel-gateway-opentelemetry-collector.observability.svc.cluster.local:4317
    attributes:
      kubernetes:
        enable: true